[package]
name = "RockPaperScissors_01"
version = "1.0.0"
authors = []
[addresses]
metaschool = "0x808b9f8be2a695f304077fb9472b9d48e54d265dbafc7892147f51d2bea7184d"
std = "0x1"
[dev-addresses]
[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
[dev-dependencies]